server:
  port: 3344
  
spring:
  application:
    name: mircoservice-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/935054692/mircoservice-config.git