server:
  port: 9527
 
spring:
  application:
    name: mircoservicecloud-zuul-gateway

eureka:
  client:
    service-url:        #服务注册到eureka服务端
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance: 
    instance-id: gateway-9527.com             #自定义服务名称信息
    prefer-ip-address: true                   #访问路径可以显示ip地址

zuul:
  ignored-services: mircoservicecloud-dept      #过滤掉真实微服务名称
  routes:     #路由映射规则配置
    mydept.serviceId: mircoservicecloud-dept
    mydept.path: /mydept/**

info:
  app.name: weiy.mircoservicecloud
  company.name: www.weiy.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$